#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  aux_sym_block_header_token1 = 1,
  sym__block_begin = 2,
  aux_sym_node_token1 = 3,
  sym_identifier = 4,
  anon_sym_AT = 5,
  sym__assignment = 6,
  sym_content = 7,
  sym_indent = 8,
  sym_dedent = 9,
  sym_newline = 10,
  sym_document = 11,
  sym__stanza = 12,
  sym__primary_node_line = 13,
  sym__primary_node = 14,
  sym__block_node_section = 15,
  sym_block = 16,
  aux_sym__block_body = 17,
  sym_block_header = 18,
  sym_children = 19,
  sym_node = 20,
  sym__node_content = 21,
  sym_ref = 22,
  sym__binder = 23,
  sym__anonymous_binder = 24,
  sym_binding = 25,
  aux_sym__stanza_repeat1 = 26,
  aux_sym__stanza_repeat2 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_block_header_token1] = "block_header_token1",
  [sym__block_begin] = "_block_begin",
  [aux_sym_node_token1] = "node_token1",
  [sym_identifier] = "identifier",
  [anon_sym_AT] = "@",
  [sym__assignment] = "_assignment",
  [sym_content] = "content",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_newline] = "newline",
  [sym_document] = "document",
  [sym__stanza] = "_stanza",
  [sym__primary_node_line] = "_primary_node_line",
  [sym__primary_node] = "_primary_node",
  [sym__block_node_section] = "_block_node_section",
  [sym_block] = "block",
  [aux_sym__block_body] = "_block_body",
  [sym_block_header] = "block_header",
  [sym_children] = "children",
  [sym_node] = "node",
  [sym__node_content] = "_node_content",
  [sym_ref] = "ref",
  [sym__binder] = "_binder",
  [sym__anonymous_binder] = "_anonymous_binder",
  [sym_binding] = "binding",
  [aux_sym__stanza_repeat1] = "_stanza_repeat1",
  [aux_sym__stanza_repeat2] = "_stanza_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_block_header_token1] = aux_sym_block_header_token1,
  [sym__block_begin] = sym__block_begin,
  [aux_sym_node_token1] = aux_sym_node_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [sym__assignment] = sym__assignment,
  [sym_content] = sym_content,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_newline] = sym_newline,
  [sym_document] = sym_document,
  [sym__stanza] = sym__stanza,
  [sym__primary_node_line] = sym__primary_node_line,
  [sym__primary_node] = sym__primary_node,
  [sym__block_node_section] = sym__block_node_section,
  [sym_block] = sym_block,
  [aux_sym__block_body] = aux_sym__block_body,
  [sym_block_header] = sym_block_header,
  [sym_children] = sym_children,
  [sym_node] = sym_node,
  [sym__node_content] = sym__node_content,
  [sym_ref] = sym_ref,
  [sym__binder] = sym__binder,
  [sym__anonymous_binder] = sym__anonymous_binder,
  [sym_binding] = sym_binding,
  [aux_sym__stanza_repeat1] = aux_sym__stanza_repeat1,
  [aux_sym__stanza_repeat2] = aux_sym__stanza_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_block_header_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__block_begin] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_node_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym__assignment] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__stanza] = {
    .visible = false,
    .named = true,
  },
  [sym__primary_node_line] = {
    .visible = false,
    .named = true,
  },
  [sym__primary_node] = {
    .visible = false,
    .named = true,
  },
  [sym__block_node_section] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__block_body] = {
    .visible = false,
    .named = false,
  },
  [sym_block_header] = {
    .visible = true,
    .named = true,
  },
  [sym_children] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym__node_content] = {
    .visible = false,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym__binder] = {
    .visible = false,
    .named = true,
  },
  [sym__anonymous_binder] = {
    .visible = false,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__stanza_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__stanza_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 12,
  [16] = 11,
  [17] = 14,
  [18] = 6,
  [19] = 13,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 22,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 27,
  [30] = 26,
  [31] = 28,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 36,
  [40] = 37,
  [41] = 35,
  [42] = 38,
  [43] = 43,
  [44] = 34,
  [45] = 43,
  [46] = 46,
  [47] = 46,
  [48] = 34,
  [49] = 34,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 52,
  [56] = 51,
  [57] = 52,
  [58] = 58,
  [59] = 54,
  [60] = 50,
  [61] = 61,
  [62] = 58,
  [63] = 61,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 64,
  [68] = 68,
  [69] = 68,
  [70] = 51,
  [71] = 51,
  [72] = 72,
  [73] = 72,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 77,
  [80] = 80,
  [81] = 81,
  [82] = 76,
  [83] = 81,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 86,
  [89] = 89,
  [90] = 89,
  [91] = 91,
  [92] = 34,
  [93] = 91,
  [94] = 94,
  [95] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '@') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '@') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(15);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 3:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '@') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '@') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(13);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_block_header_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym__block_begin);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_node_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__assignment);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4, .external_lex_state = 2},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4, .external_lex_state = 3},
  [7] = {.lex_state = 4, .external_lex_state = 3},
  [8] = {.lex_state = 4, .external_lex_state = 4},
  [9] = {.lex_state = 4, .external_lex_state = 4},
  [10] = {.lex_state = 4, .external_lex_state = 3},
  [11] = {.lex_state = 4, .external_lex_state = 4},
  [12] = {.lex_state = 4, .external_lex_state = 3},
  [13] = {.lex_state = 4, .external_lex_state = 4},
  [14] = {.lex_state = 4, .external_lex_state = 4},
  [15] = {.lex_state = 4, .external_lex_state = 4},
  [16] = {.lex_state = 4, .external_lex_state = 3},
  [17] = {.lex_state = 4, .external_lex_state = 3},
  [18] = {.lex_state = 4, .external_lex_state = 4},
  [19] = {.lex_state = 4, .external_lex_state = 3},
  [20] = {.lex_state = 4, .external_lex_state = 2},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 3, .external_lex_state = 5},
  [35] = {.lex_state = 1, .external_lex_state = 6},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4, .external_lex_state = 5},
  [38] = {.lex_state = 3, .external_lex_state = 1},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4, .external_lex_state = 1},
  [41] = {.lex_state = 1, .external_lex_state = 6},
  [42] = {.lex_state = 3, .external_lex_state = 5},
  [43] = {.lex_state = 4, .external_lex_state = 5},
  [44] = {.lex_state = 3, .external_lex_state = 1},
  [45] = {.lex_state = 4, .external_lex_state = 1},
  [46] = {.lex_state = 4, .external_lex_state = 1},
  [47] = {.lex_state = 4, .external_lex_state = 5},
  [48] = {.lex_state = 4, .external_lex_state = 1},
  [49] = {.lex_state = 4, .external_lex_state = 5},
  [50] = {.lex_state = 4, .external_lex_state = 4},
  [51] = {.lex_state = 4, .external_lex_state = 3},
  [52] = {.lex_state = 4, .external_lex_state = 3},
  [53] = {.lex_state = 4, .external_lex_state = 4},
  [54] = {.lex_state = 4, .external_lex_state = 4},
  [55] = {.lex_state = 4, .external_lex_state = 4},
  [56] = {.lex_state = 4, .external_lex_state = 4},
  [57] = {.lex_state = 4, .external_lex_state = 3},
  [58] = {.lex_state = 4, .external_lex_state = 4},
  [59] = {.lex_state = 4, .external_lex_state = 3},
  [60] = {.lex_state = 4, .external_lex_state = 3},
  [61] = {.lex_state = 4, .external_lex_state = 4},
  [62] = {.lex_state = 4, .external_lex_state = 3},
  [63] = {.lex_state = 4, .external_lex_state = 3},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 4, .external_lex_state = 4},
  [66] = {.lex_state = 4, .external_lex_state = 3},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0, .external_lex_state = 4},
  [69] = {.lex_state = 0, .external_lex_state = 3},
  [70] = {.lex_state = 4, .external_lex_state = 2},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0, .external_lex_state = 2},
  [74] = {.lex_state = 8, .external_lex_state = 4},
  [75] = {.lex_state = 8, .external_lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 8, .external_lex_state = 4},
  [81] = {.lex_state = 8, .external_lex_state = 4},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 8, .external_lex_state = 4},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0, .external_lex_state = 4},
  [95] = {.lex_state = 0, .external_lex_state = 4},
};

enum {
  ts_external_token_indent = 0,
  ts_external_token_dedent = 1,
  ts_external_token_newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token_newline] = sym_newline,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_newline] = true,
  },
  [2] = {
    [ts_external_token_dedent] = true,
  },
  [3] = {
    [ts_external_token_dedent] = true,
    [ts_external_token_newline] = true,
  },
  [4] = {
    [ts_external_token_newline] = true,
  },
  [5] = {
    [ts_external_token_indent] = true,
    [ts_external_token_newline] = true,
  },
  [6] = {
    [ts_external_token_indent] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__block_begin] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym__assignment] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(84),
    [sym__stanza] = STATE(87),
    [sym__primary_node_line] = STATE(5),
    [sym__primary_node] = STATE(55),
    [sym__block_node_section] = STATE(27),
    [sym_block] = STATE(68),
    [sym_block_header] = STATE(8),
    [sym_node] = STATE(55),
    [sym__node_content] = STATE(43),
    [sym_ref] = STATE(43),
    [sym__binder] = STATE(42),
    [sym__anonymous_binder] = STATE(85),
    [sym_binding] = STATE(83),
    [aux_sym__stanza_repeat1] = STATE(5),
    [aux_sym__stanza_repeat2] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__block_begin] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [sym_content] = ACTIONS(9),
  },
  [2] = {
    [sym__stanza] = STATE(89),
    [sym__primary_node_line] = STATE(4),
    [sym__primary_node] = STATE(57),
    [sym__block_node_section] = STATE(29),
    [sym_block] = STATE(69),
    [sym_block_header] = STATE(10),
    [sym_node] = STATE(57),
    [sym__node_content] = STATE(45),
    [sym_ref] = STATE(45),
    [sym__binder] = STATE(38),
    [sym__anonymous_binder] = STATE(85),
    [sym_binding] = STATE(81),
    [aux_sym__stanza_repeat1] = STATE(4),
    [aux_sym__stanza_repeat2] = STATE(29),
    [sym__block_begin] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [sym_content] = ACTIONS(15),
  },
  [3] = {
    [sym__stanza] = STATE(90),
    [sym__primary_node_line] = STATE(4),
    [sym__primary_node] = STATE(57),
    [sym__block_node_section] = STATE(29),
    [sym_block] = STATE(69),
    [sym_block_header] = STATE(10),
    [sym_node] = STATE(57),
    [sym__node_content] = STATE(45),
    [sym_ref] = STATE(45),
    [sym__binder] = STATE(38),
    [sym__anonymous_binder] = STATE(85),
    [sym_binding] = STATE(81),
    [aux_sym__stanza_repeat1] = STATE(4),
    [aux_sym__stanza_repeat2] = STATE(29),
    [sym__block_begin] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [sym_content] = ACTIONS(15),
  },
  [4] = {
    [sym__primary_node_line] = STATE(20),
    [sym__primary_node] = STATE(57),
    [sym__block_node_section] = STATE(31),
    [sym_block] = STATE(69),
    [sym_block_header] = STATE(10),
    [sym_node] = STATE(57),
    [sym__node_content] = STATE(45),
    [sym_ref] = STATE(45),
    [sym__binder] = STATE(38),
    [sym__anonymous_binder] = STATE(85),
    [sym_binding] = STATE(81),
    [aux_sym__stanza_repeat1] = STATE(20),
    [aux_sym__stanza_repeat2] = STATE(31),
    [sym__block_begin] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [sym_content] = ACTIONS(15),
    [sym_dedent] = ACTIONS(17),
  },
  [5] = {
    [sym__primary_node_line] = STATE(21),
    [sym__primary_node] = STATE(55),
    [sym__block_node_section] = STATE(28),
    [sym_block] = STATE(68),
    [sym_block_header] = STATE(8),
    [sym_node] = STATE(55),
    [sym__node_content] = STATE(43),
    [sym_ref] = STATE(43),
    [sym__binder] = STATE(42),
    [sym__anonymous_binder] = STATE(85),
    [sym_binding] = STATE(83),
    [aux_sym__stanza_repeat1] = STATE(21),
    [aux_sym__stanza_repeat2] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym__block_begin] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [sym_content] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(19), 1,
      sym__block_begin,
    ACTIONS(21), 1,
      anon_sym_AT,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(24), 2,
      sym_dedent,
      sym_newline,
    STATE(19), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [35] = 10,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(26), 1,
      sym__block_begin,
    ACTIONS(28), 1,
      anon_sym_AT,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(31), 2,
      sym_dedent,
      sym_newline,
    STATE(19), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [70] = 11,
    ACTIONS(9), 1,
      sym_content,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym__block_begin,
    ACTIONS(37), 1,
      anon_sym_AT,
    ACTIONS(40), 1,
      sym_newline,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(18), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [107] = 10,
    ACTIONS(9), 1,
      sym_content,
    ACTIONS(26), 1,
      sym__block_begin,
    ACTIONS(43), 1,
      anon_sym_AT,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(31), 2,
      sym_newline,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [142] = 11,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(33), 1,
      sym_dedent,
    ACTIONS(35), 1,
      sym__block_begin,
    ACTIONS(46), 1,
      anon_sym_AT,
    ACTIONS(49), 1,
      sym_newline,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(6), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [179] = 11,
    ACTIONS(9), 1,
      sym_content,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym__block_begin,
    ACTIONS(56), 1,
      anon_sym_AT,
    ACTIONS(59), 1,
      sym_newline,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(9), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [216] = 10,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(62), 1,
      sym__block_begin,
    ACTIONS(64), 1,
      anon_sym_AT,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(67), 2,
      sym_dedent,
      sym_newline,
    STATE(19), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [251] = 10,
    ACTIONS(71), 1,
      sym__block_begin,
    ACTIONS(73), 1,
      anon_sym_AT,
    ACTIONS(76), 1,
      sym_content,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(69), 2,
      sym_newline,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [286] = 10,
    ACTIONS(9), 1,
      sym_content,
    ACTIONS(54), 1,
      sym__block_begin,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(52), 2,
      sym_newline,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [321] = 10,
    ACTIONS(9), 1,
      sym_content,
    ACTIONS(62), 1,
      sym__block_begin,
    ACTIONS(79), 1,
      anon_sym_AT,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(67), 2,
      sym_newline,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [356] = 11,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(52), 1,
      sym_dedent,
    ACTIONS(54), 1,
      sym__block_begin,
    ACTIONS(82), 1,
      anon_sym_AT,
    ACTIONS(85), 1,
      sym_newline,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(7), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [393] = 10,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(54), 1,
      sym__block_begin,
    ACTIONS(82), 1,
      anon_sym_AT,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(52), 2,
      sym_dedent,
      sym_newline,
    STATE(19), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [428] = 10,
    ACTIONS(9), 1,
      sym_content,
    ACTIONS(19), 1,
      sym__block_begin,
    ACTIONS(88), 1,
      anon_sym_AT,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(24), 2,
      sym_newline,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [463] = 10,
    ACTIONS(71), 1,
      sym__block_begin,
    ACTIONS(91), 1,
      anon_sym_AT,
    ACTIONS(94), 1,
      sym_content,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    ACTIONS(69), 2,
      sym_dedent,
      sym_newline,
    STATE(19), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [498] = 10,
    ACTIONS(97), 1,
      sym__block_begin,
    ACTIONS(99), 1,
      anon_sym_AT,
    ACTIONS(102), 1,
      sym_content,
    ACTIONS(105), 1,
      sym_dedent,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(20), 2,
      sym__primary_node_line,
      aux_sym__stanza_repeat1,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(57), 2,
      sym__primary_node,
      sym_node,
  [532] = 10,
    ACTIONS(97), 1,
      sym__block_begin,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(110), 1,
      sym_content,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(21), 2,
      sym__primary_node_line,
      aux_sym__stanza_repeat1,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(55), 2,
      sym__primary_node,
      sym_node,
  [566] = 8,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_content,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(12), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [594] = 8,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_content,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(17), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(52), 2,
      sym__primary_node,
      sym_node,
  [622] = 8,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(9), 1,
      sym_content,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(14), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [650] = 8,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(9), 1,
      sym_content,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(15), 2,
      sym__primary_node_line,
      aux_sym__block_body,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(53), 2,
      sym__primary_node,
      sym_node,
  [678] = 8,
    ACTIONS(113), 1,
      sym__block_begin,
    ACTIONS(116), 1,
      anon_sym_AT,
    ACTIONS(119), 1,
      sym_dedent,
    STATE(10), 1,
      sym_block_header,
    STATE(69), 1,
      sym_block,
    STATE(95), 1,
      sym_binding,
    STATE(26), 2,
      sym__block_node_section,
      aux_sym__stanza_repeat2,
    STATE(85), 2,
      sym__binder,
      sym__anonymous_binder,
  [705] = 8,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 1,
      sym__block_begin,
    ACTIONS(123), 1,
      anon_sym_AT,
    STATE(8), 1,
      sym_block_header,
    STATE(68), 1,
      sym_block,
    STATE(94), 1,
      sym_binding,
    STATE(30), 2,
      sym__block_node_section,
      aux_sym__stanza_repeat2,
    STATE(85), 2,
      sym__binder,
      sym__anonymous_binder,
  [732] = 8,
    ACTIONS(121), 1,
      sym__block_begin,
    ACTIONS(123), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_block_header,
    STATE(68), 1,
      sym_block,
    STATE(94), 1,
      sym_binding,
    STATE(30), 2,
      sym__block_node_section,
      aux_sym__stanza_repeat2,
    STATE(85), 2,
      sym__binder,
      sym__anonymous_binder,
  [759] = 8,
    ACTIONS(17), 1,
      sym_dedent,
    ACTIONS(123), 1,
      anon_sym_AT,
    ACTIONS(127), 1,
      sym__block_begin,
    STATE(10), 1,
      sym_block_header,
    STATE(69), 1,
      sym_block,
    STATE(95), 1,
      sym_binding,
    STATE(26), 2,
      sym__block_node_section,
      aux_sym__stanza_repeat2,
    STATE(85), 2,
      sym__binder,
      sym__anonymous_binder,
  [786] = 8,
    ACTIONS(116), 1,
      anon_sym_AT,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 1,
      sym__block_begin,
    STATE(8), 1,
      sym_block_header,
    STATE(68), 1,
      sym_block,
    STATE(94), 1,
      sym_binding,
    STATE(30), 2,
      sym__block_node_section,
      aux_sym__stanza_repeat2,
    STATE(85), 2,
      sym__binder,
      sym__anonymous_binder,
  [813] = 8,
    ACTIONS(123), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      sym_dedent,
    ACTIONS(127), 1,
      sym__block_begin,
    STATE(10), 1,
      sym_block_header,
    STATE(69), 1,
      sym_block,
    STATE(95), 1,
      sym_binding,
    STATE(26), 2,
      sym__block_node_section,
      aux_sym__stanza_repeat2,
    STATE(85), 2,
      sym__binder,
      sym__anonymous_binder,
  [840] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_content,
    STATE(38), 1,
      sym__binder,
    STATE(74), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(45), 2,
      sym__node_content,
      sym_ref,
    STATE(66), 2,
      sym__primary_node,
      sym_node,
  [864] = 7,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(9), 1,
      sym_content,
    STATE(42), 1,
      sym__binder,
    STATE(75), 1,
      sym_binding,
    STATE(85), 1,
      sym__anonymous_binder,
    STATE(43), 2,
      sym__node_content,
      sym_ref,
    STATE(65), 2,
      sym__primary_node,
      sym_node,
  [888] = 2,
    ACTIONS(132), 3,
      sym_indent,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(134), 4,
      sym__block_begin,
      anon_sym_AT,
      sym__assignment,
      sym_content,
  [900] = 6,
    ACTIONS(136), 1,
      anon_sym_AT,
    ACTIONS(138), 1,
      sym_content,
    ACTIONS(140), 1,
      sym_indent,
    STATE(46), 1,
      sym__binder,
    STATE(63), 1,
      sym_children,
    STATE(40), 2,
      sym__node_content,
      sym_ref,
  [920] = 6,
    ACTIONS(11), 1,
      sym__block_begin,
    ACTIONS(136), 1,
      anon_sym_AT,
    ACTIONS(138), 1,
      sym_content,
    STATE(16), 1,
      sym_block_header,
    STATE(46), 1,
      sym__binder,
    STATE(40), 2,
      sym__node_content,
      sym_ref,
  [940] = 4,
    ACTIONS(146), 1,
      sym_indent,
    STATE(54), 1,
      sym_children,
    ACTIONS(142), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(144), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [956] = 3,
    ACTIONS(150), 1,
      sym__assignment,
    ACTIONS(148), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
    ACTIONS(152), 3,
      sym_indent,
      sym_dedent,
      sym_newline,
  [970] = 6,
    ACTIONS(5), 1,
      sym__block_begin,
    ACTIONS(154), 1,
      anon_sym_AT,
    ACTIONS(156), 1,
      sym_content,
    STATE(11), 1,
      sym_block_header,
    STATE(47), 1,
      sym__binder,
    STATE(37), 2,
      sym__node_content,
      sym_ref,
  [990] = 4,
    ACTIONS(140), 1,
      sym_indent,
    STATE(59), 1,
      sym_children,
    ACTIONS(142), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(144), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1006] = 6,
    ACTIONS(146), 1,
      sym_indent,
    ACTIONS(154), 1,
      anon_sym_AT,
    ACTIONS(156), 1,
      sym_content,
    STATE(47), 1,
      sym__binder,
    STATE(61), 1,
      sym_children,
    STATE(37), 2,
      sym__node_content,
      sym_ref,
  [1026] = 3,
    ACTIONS(150), 1,
      sym__assignment,
    ACTIONS(148), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
    ACTIONS(152), 3,
      sym_indent,
      sym_newline,
      ts_builtin_sym_end,
  [1040] = 4,
    ACTIONS(146), 1,
      sym_indent,
    STATE(50), 1,
      sym_children,
    ACTIONS(158), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(160), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1056] = 2,
    ACTIONS(132), 3,
      sym_indent,
      sym_dedent,
      sym_newline,
    ACTIONS(134), 4,
      sym__block_begin,
      anon_sym_AT,
      sym__assignment,
      sym_content,
  [1068] = 4,
    ACTIONS(140), 1,
      sym_indent,
    STATE(60), 1,
      sym_children,
    ACTIONS(158), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(160), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1084] = 2,
    ACTIONS(148), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
    ACTIONS(152), 3,
      sym_indent,
      sym_dedent,
      sym_newline,
  [1095] = 2,
    ACTIONS(148), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
    ACTIONS(152), 3,
      sym_indent,
      sym_newline,
      ts_builtin_sym_end,
  [1106] = 2,
    ACTIONS(132), 3,
      sym_indent,
      sym_dedent,
      sym_newline,
    ACTIONS(134), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1117] = 2,
    ACTIONS(132), 3,
      sym_indent,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(134), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1128] = 2,
    ACTIONS(162), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(164), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1138] = 2,
    ACTIONS(168), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(166), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1148] = 3,
    ACTIONS(172), 1,
      sym_dedent,
    ACTIONS(174), 1,
      sym_newline,
    ACTIONS(170), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1160] = 3,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(177), 1,
      sym_newline,
    ACTIONS(170), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1172] = 2,
    ACTIONS(180), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(182), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1182] = 3,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(184), 1,
      sym_newline,
    ACTIONS(170), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1194] = 2,
    ACTIONS(168), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(166), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1204] = 3,
    ACTIONS(172), 1,
      sym_dedent,
    ACTIONS(186), 1,
      sym_newline,
    ACTIONS(170), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1216] = 2,
    ACTIONS(188), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(190), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1226] = 2,
    ACTIONS(180), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(182), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1236] = 2,
    ACTIONS(162), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(164), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1246] = 2,
    ACTIONS(142), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(144), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1256] = 2,
    ACTIONS(188), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(190), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1266] = 2,
    ACTIONS(142), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(144), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1276] = 4,
    ACTIONS(154), 1,
      anon_sym_AT,
    ACTIONS(156), 1,
      sym_content,
    STATE(47), 1,
      sym__binder,
    STATE(37), 2,
      sym__node_content,
      sym_ref,
  [1290] = 2,
    ACTIONS(192), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(194), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1300] = 2,
    ACTIONS(192), 2,
      sym_dedent,
      sym_newline,
    ACTIONS(194), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1310] = 4,
    ACTIONS(136), 1,
      anon_sym_AT,
    ACTIONS(138), 1,
      sym_content,
    STATE(46), 1,
      sym__binder,
    STATE(40), 2,
      sym__node_content,
      sym_ref,
  [1324] = 2,
    ACTIONS(198), 1,
      sym_newline,
    ACTIONS(196), 3,
      ts_builtin_sym_end,
      sym__block_begin,
      anon_sym_AT,
  [1333] = 2,
    ACTIONS(200), 1,
      sym_newline,
    ACTIONS(196), 3,
      sym_dedent,
      sym__block_begin,
      anon_sym_AT,
  [1342] = 2,
    ACTIONS(168), 1,
      sym_dedent,
    ACTIONS(166), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1351] = 2,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 3,
      sym__block_begin,
      anon_sym_AT,
      sym_content,
  [1360] = 1,
    ACTIONS(202), 3,
      ts_builtin_sym_end,
      sym__block_begin,
      anon_sym_AT,
  [1366] = 1,
    ACTIONS(202), 3,
      sym_dedent,
      sym__block_begin,
      anon_sym_AT,
  [1372] = 2,
    ACTIONS(204), 1,
      aux_sym_node_token1,
    ACTIONS(206), 1,
      sym_newline,
  [1379] = 2,
    ACTIONS(208), 1,
      aux_sym_node_token1,
    ACTIONS(210), 1,
      sym_newline,
  [1386] = 2,
    ACTIONS(212), 1,
      sym_identifier,
    ACTIONS(214), 1,
      sym__assignment,
  [1393] = 2,
    ACTIONS(121), 1,
      sym__block_begin,
    STATE(11), 1,
      sym_block_header,
  [1400] = 2,
    ACTIONS(214), 1,
      sym__assignment,
    ACTIONS(216), 1,
      sym_identifier,
  [1407] = 2,
    ACTIONS(127), 1,
      sym__block_begin,
    STATE(16), 1,
      sym_block_header,
  [1414] = 1,
    ACTIONS(218), 2,
      sym_newline,
      aux_sym_node_token1,
  [1419] = 2,
    ACTIONS(204), 1,
      aux_sym_node_token1,
    ACTIONS(220), 1,
      sym_newline,
  [1426] = 2,
    ACTIONS(214), 1,
      sym__assignment,
    ACTIONS(222), 1,
      sym_identifier,
  [1433] = 2,
    ACTIONS(208), 1,
      aux_sym_node_token1,
    ACTIONS(224), 1,
      sym_newline,
  [1440] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [1444] = 1,
    ACTIONS(228), 1,
      sym__assignment,
  [1448] = 1,
    ACTIONS(230), 1,
      aux_sym_block_header_token1,
  [1452] = 1,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
  [1456] = 1,
    ACTIONS(234), 1,
      aux_sym_block_header_token1,
  [1460] = 1,
    ACTIONS(236), 1,
      sym_dedent,
  [1464] = 1,
    ACTIONS(238), 1,
      sym_dedent,
  [1468] = 1,
    ACTIONS(240), 1,
      sym_identifier,
  [1472] = 1,
    ACTIONS(132), 1,
      sym__assignment,
  [1476] = 1,
    ACTIONS(242), 1,
      sym_identifier,
  [1480] = 1,
    ACTIONS(244), 1,
      sym_newline,
  [1484] = 1,
    ACTIONS(246), 1,
      sym_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 35,
  [SMALL_STATE(8)] = 70,
  [SMALL_STATE(9)] = 107,
  [SMALL_STATE(10)] = 142,
  [SMALL_STATE(11)] = 179,
  [SMALL_STATE(12)] = 216,
  [SMALL_STATE(13)] = 251,
  [SMALL_STATE(14)] = 286,
  [SMALL_STATE(15)] = 321,
  [SMALL_STATE(16)] = 356,
  [SMALL_STATE(17)] = 393,
  [SMALL_STATE(18)] = 428,
  [SMALL_STATE(19)] = 463,
  [SMALL_STATE(20)] = 498,
  [SMALL_STATE(21)] = 532,
  [SMALL_STATE(22)] = 566,
  [SMALL_STATE(23)] = 594,
  [SMALL_STATE(24)] = 622,
  [SMALL_STATE(25)] = 650,
  [SMALL_STATE(26)] = 678,
  [SMALL_STATE(27)] = 705,
  [SMALL_STATE(28)] = 732,
  [SMALL_STATE(29)] = 759,
  [SMALL_STATE(30)] = 786,
  [SMALL_STATE(31)] = 813,
  [SMALL_STATE(32)] = 840,
  [SMALL_STATE(33)] = 864,
  [SMALL_STATE(34)] = 888,
  [SMALL_STATE(35)] = 900,
  [SMALL_STATE(36)] = 920,
  [SMALL_STATE(37)] = 940,
  [SMALL_STATE(38)] = 956,
  [SMALL_STATE(39)] = 970,
  [SMALL_STATE(40)] = 990,
  [SMALL_STATE(41)] = 1006,
  [SMALL_STATE(42)] = 1026,
  [SMALL_STATE(43)] = 1040,
  [SMALL_STATE(44)] = 1056,
  [SMALL_STATE(45)] = 1068,
  [SMALL_STATE(46)] = 1084,
  [SMALL_STATE(47)] = 1095,
  [SMALL_STATE(48)] = 1106,
  [SMALL_STATE(49)] = 1117,
  [SMALL_STATE(50)] = 1128,
  [SMALL_STATE(51)] = 1138,
  [SMALL_STATE(52)] = 1148,
  [SMALL_STATE(53)] = 1160,
  [SMALL_STATE(54)] = 1172,
  [SMALL_STATE(55)] = 1182,
  [SMALL_STATE(56)] = 1194,
  [SMALL_STATE(57)] = 1204,
  [SMALL_STATE(58)] = 1216,
  [SMALL_STATE(59)] = 1226,
  [SMALL_STATE(60)] = 1236,
  [SMALL_STATE(61)] = 1246,
  [SMALL_STATE(62)] = 1256,
  [SMALL_STATE(63)] = 1266,
  [SMALL_STATE(64)] = 1276,
  [SMALL_STATE(65)] = 1290,
  [SMALL_STATE(66)] = 1300,
  [SMALL_STATE(67)] = 1310,
  [SMALL_STATE(68)] = 1324,
  [SMALL_STATE(69)] = 1333,
  [SMALL_STATE(70)] = 1342,
  [SMALL_STATE(71)] = 1351,
  [SMALL_STATE(72)] = 1360,
  [SMALL_STATE(73)] = 1366,
  [SMALL_STATE(74)] = 1372,
  [SMALL_STATE(75)] = 1379,
  [SMALL_STATE(76)] = 1386,
  [SMALL_STATE(77)] = 1393,
  [SMALL_STATE(78)] = 1400,
  [SMALL_STATE(79)] = 1407,
  [SMALL_STATE(80)] = 1414,
  [SMALL_STATE(81)] = 1419,
  [SMALL_STATE(82)] = 1426,
  [SMALL_STATE(83)] = 1433,
  [SMALL_STATE(84)] = 1440,
  [SMALL_STATE(85)] = 1444,
  [SMALL_STATE(86)] = 1448,
  [SMALL_STATE(87)] = 1452,
  [SMALL_STATE(88)] = 1456,
  [SMALL_STATE(89)] = 1460,
  [SMALL_STATE(90)] = 1464,
  [SMALL_STATE(91)] = 1468,
  [SMALL_STATE(92)] = 1472,
  [SMALL_STATE(93)] = 1476,
  [SMALL_STATE(94)] = 1480,
  [SMALL_STATE(95)] = 1484,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stanza, 1),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 2), SHIFT(78),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 4), SHIFT(78),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 1), SHIFT(76),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block, 1), SHIFT(24),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 4), SHIFT(76),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 1), SHIFT(78),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block, 1), SHIFT(23),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 3), SHIFT(76),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block, 3), SHIFT(25),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 5),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 5), SHIFT(78),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_body, 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block_body, 2),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_body, 2), SHIFT_REPEAT(76),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_body, 2), SHIFT_REPEAT(43),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 5), SHIFT(76),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 3), SHIFT(78),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_block, 3), SHIFT(22),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_block, 2), SHIFT(76),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_body, 2), SHIFT_REPEAT(78),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_body, 2), SHIFT_REPEAT(45),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__stanza_repeat1, 2),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stanza_repeat1, 2), SHIFT_REPEAT(78),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stanza_repeat1, 2), SHIFT_REPEAT(45),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__stanza_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stanza_repeat1, 2), SHIFT_REPEAT(76),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stanza_repeat1, 2), SHIFT_REPEAT(43),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stanza_repeat2, 2), SHIFT_REPEAT(86),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stanza_repeat2, 2), SHIFT_REPEAT(82),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__stanza_repeat2, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stanza, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stanza_repeat2, 2), SHIFT_REPEAT(88),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binder, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__binder, 2),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 1),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary_node_line, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_node_line, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary_node_line, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_node_line, 1),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__primary_node_line, 1), SHIFT(51),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__primary_node_line, 1), SHIFT(56),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 4),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 3),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_children, 3),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_header, 3),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_header, 3),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_node_section, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_node_section, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anonymous_binder, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_puddlejumper_external_scanner_create(void);
void tree_sitter_puddlejumper_external_scanner_destroy(void *);
bool tree_sitter_puddlejumper_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_puddlejumper_external_scanner_serialize(void *, char *);
void tree_sitter_puddlejumper_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_puddlejumper(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_puddlejumper_external_scanner_create,
      tree_sitter_puddlejumper_external_scanner_destroy,
      tree_sitter_puddlejumper_external_scanner_scan,
      tree_sitter_puddlejumper_external_scanner_serialize,
      tree_sitter_puddlejumper_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
