#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  aux_sym_block_node_token1 = 2,
  anon_sym_AT = 3,
  anon_sym_COLON = 4,
  anon_sym_AT2 = 5,
  sym_content = 6,
  sym_indent = 7,
  sym_dedent = 8,
  sym_newline = 9,
  sym_mega_newline = 10,
  sym_document = 11,
  aux_sym__stanza = 12,
  sym__primary_node = 13,
  sym_block_node = 14,
  sym_node = 15,
  sym_ref_node = 16,
  sym_children = 17,
  sym_binding = 18,
  sym_ref = 19,
  aux_sym_block_node_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_block_node_token1] = "block_node_token1",
  [anon_sym_AT] = "@",
  [anon_sym_COLON] = ":",
  [anon_sym_AT2] = "@",
  [sym_content] = "content",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_newline] = "newline",
  [sym_mega_newline] = "mega_newline",
  [sym_document] = "document",
  [aux_sym__stanza] = "_stanza",
  [sym__primary_node] = "_primary_node",
  [sym_block_node] = "block_node",
  [sym_node] = "node",
  [sym_ref_node] = "ref_node",
  [sym_children] = "children",
  [sym_binding] = "binding",
  [sym_ref] = "ref",
  [aux_sym_block_node_repeat1] = "block_node_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_block_node_token1] = aux_sym_block_node_token1,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_AT2] = anon_sym_AT,
  [sym_content] = sym_content,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_newline] = sym_newline,
  [sym_mega_newline] = sym_mega_newline,
  [sym_document] = sym_document,
  [aux_sym__stanza] = aux_sym__stanza,
  [sym__primary_node] = sym__primary_node,
  [sym_block_node] = sym_block_node,
  [sym_node] = sym_node,
  [sym_ref_node] = sym_ref_node,
  [sym_children] = sym_children,
  [sym_binding] = sym_binding,
  [sym_ref] = sym_ref,
  [aux_sym_block_node_repeat1] = aux_sym_block_node_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_node_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT2] = {
    .visible = true,
    .named = false,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_mega_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__stanza] = {
    .visible = false,
    .named = false,
  },
  [sym__primary_node] = {
    .visible = false,
    .named = true,
  },
  [sym_block_node] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_node] = {
    .visible = true,
    .named = true,
  },
  [sym_children] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_node_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 4,
  [7] = 4,
  [8] = 2,
  [9] = 9,
  [10] = 9,
  [11] = 9,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 14,
  [17] = 13,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 14,
  [22] = 18,
  [23] = 14,
  [24] = 20,
  [25] = 13,
  [26] = 19,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 30,
  [34] = 31,
  [35] = 32,
  [36] = 27,
  [37] = 30,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 38,
  [42] = 31,
  [43] = 27,
  [44] = 27,
  [45] = 39,
  [46] = 30,
  [47] = 40,
  [48] = 31,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 50,
  [53] = 53,
  [54] = 53,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 62,
  [64] = 61,
  [65] = 56,
  [66] = 66,
  [67] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_block_node_token1);
      if (eof) ADVANCE(3);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(8);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym_block_node_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2, .external_lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2, .external_lex_state = 2},
  [5] = {.lex_state = 2, .external_lex_state = 2},
  [6] = {.lex_state = 2, .external_lex_state = 2},
  [7] = {.lex_state = 2, .external_lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2, .external_lex_state = 1},
  [14] = {.lex_state = 2, .external_lex_state = 3},
  [15] = {.lex_state = 2, .external_lex_state = 3},
  [16] = {.lex_state = 2, .external_lex_state = 1},
  [17] = {.lex_state = 2, .external_lex_state = 4},
  [18] = {.lex_state = 2, .external_lex_state = 5},
  [19] = {.lex_state = 2, .external_lex_state = 6},
  [20] = {.lex_state = 2, .external_lex_state = 6},
  [21] = {.lex_state = 2, .external_lex_state = 5},
  [22] = {.lex_state = 2, .external_lex_state = 4},
  [23] = {.lex_state = 2, .external_lex_state = 4},
  [24] = {.lex_state = 2, .external_lex_state = 7},
  [25] = {.lex_state = 2, .external_lex_state = 5},
  [26] = {.lex_state = 2, .external_lex_state = 7},
  [27] = {.lex_state = 2, .external_lex_state = 7},
  [28] = {.lex_state = 2, .external_lex_state = 6},
  [29] = {.lex_state = 2, .external_lex_state = 7},
  [30] = {.lex_state = 2, .external_lex_state = 7},
  [31] = {.lex_state = 2, .external_lex_state = 7},
  [32] = {.lex_state = 2, .external_lex_state = 4},
  [33] = {.lex_state = 2, .external_lex_state = 6},
  [34] = {.lex_state = 2, .external_lex_state = 6},
  [35] = {.lex_state = 2, .external_lex_state = 5},
  [36] = {.lex_state = 2, .external_lex_state = 6},
  [37] = {.lex_state = 2, .external_lex_state = 8},
  [38] = {.lex_state = 2, .external_lex_state = 9},
  [39] = {.lex_state = 2, .external_lex_state = 8},
  [40] = {.lex_state = 2, .external_lex_state = 8},
  [41] = {.lex_state = 2, .external_lex_state = 10},
  [42] = {.lex_state = 2, .external_lex_state = 8},
  [43] = {.lex_state = 2, .external_lex_state = 11},
  [44] = {.lex_state = 2, .external_lex_state = 8},
  [45] = {.lex_state = 2, .external_lex_state = 11},
  [46] = {.lex_state = 2, .external_lex_state = 11},
  [47] = {.lex_state = 2, .external_lex_state = 11},
  [48] = {.lex_state = 2, .external_lex_state = 11},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2, .external_lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2, .external_lex_state = 11},
  [54] = {.lex_state = 2, .external_lex_state = 11},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
};

enum {
  ts_external_token_indent = 0,
  ts_external_token_dedent = 1,
  ts_external_token_newline = 2,
  ts_external_token_mega_newline = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token_newline] = sym_newline,
  [ts_external_token_mega_newline] = sym_mega_newline,
};

static const bool ts_external_scanner_states[12][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_newline] = true,
    [ts_external_token_mega_newline] = true,
  },
  [2] = {
    [ts_external_token_dedent] = true,
  },
  [3] = {
    [ts_external_token_indent] = true,
    [ts_external_token_newline] = true,
    [ts_external_token_mega_newline] = true,
  },
  [4] = {
    [ts_external_token_indent] = true,
    [ts_external_token_newline] = true,
  },
  [5] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_newline] = true,
  },
  [6] = {
    [ts_external_token_dedent] = true,
    [ts_external_token_newline] = true,
    [ts_external_token_mega_newline] = true,
  },
  [7] = {
    [ts_external_token_newline] = true,
    [ts_external_token_mega_newline] = true,
  },
  [8] = {
    [ts_external_token_dedent] = true,
    [ts_external_token_newline] = true,
  },
  [9] = {
    [ts_external_token_dedent] = true,
    [ts_external_token_mega_newline] = true,
  },
  [10] = {
    [ts_external_token_mega_newline] = true,
  },
  [11] = {
    [ts_external_token_newline] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_block_node_token1] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_AT2] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_mega_newline] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(66),
    [aux_sym__stanza] = STATE(3),
    [sym__primary_node] = STATE(47),
    [sym_block_node] = STATE(41),
    [sym_node] = STATE(47),
    [sym_ref_node] = STATE(47),
    [sym_binding] = STATE(62),
    [sym_ref] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(5),
    [anon_sym_AT2] = ACTIONS(7),
    [sym_content] = ACTIONS(9),
  },
  [2] = {
    [aux_sym__stanza] = STATE(2),
    [sym__primary_node] = STATE(40),
    [sym_block_node] = STATE(38),
    [sym_node] = STATE(40),
    [sym_ref_node] = STATE(40),
    [sym_binding] = STATE(63),
    [sym_ref] = STATE(18),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_AT2] = ACTIONS(14),
    [sym_content] = ACTIONS(17),
    [sym_dedent] = ACTIONS(20),
  },
  [3] = {
    [aux_sym__stanza] = STATE(8),
    [sym__primary_node] = STATE(47),
    [sym_block_node] = STATE(41),
    [sym_node] = STATE(47),
    [sym_ref_node] = STATE(47),
    [sym_binding] = STATE(62),
    [sym_ref] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(22),
    [anon_sym_AT] = ACTIONS(5),
    [anon_sym_AT2] = ACTIONS(7),
    [sym_content] = ACTIONS(9),
  },
  [4] = {
    [aux_sym__stanza] = STATE(2),
    [sym__primary_node] = STATE(40),
    [sym_block_node] = STATE(38),
    [sym_node] = STATE(40),
    [sym_ref_node] = STATE(40),
    [sym_binding] = STATE(63),
    [sym_ref] = STATE(18),
    [anon_sym_AT] = ACTIONS(5),
    [anon_sym_AT2] = ACTIONS(24),
    [sym_content] = ACTIONS(26),
    [sym_dedent] = ACTIONS(28),
  },
  [5] = {
    [aux_sym__stanza] = STATE(2),
    [sym__primary_node] = STATE(40),
    [sym_block_node] = STATE(38),
    [sym_node] = STATE(40),
    [sym_ref_node] = STATE(40),
    [sym_binding] = STATE(63),
    [sym_ref] = STATE(18),
    [anon_sym_AT] = ACTIONS(5),
    [anon_sym_AT2] = ACTIONS(24),
    [sym_content] = ACTIONS(26),
    [sym_dedent] = ACTIONS(30),
  },
  [6] = {
    [aux_sym__stanza] = STATE(2),
    [sym__primary_node] = STATE(40),
    [sym_block_node] = STATE(38),
    [sym_node] = STATE(40),
    [sym_ref_node] = STATE(40),
    [sym_binding] = STATE(63),
    [sym_ref] = STATE(18),
    [anon_sym_AT] = ACTIONS(5),
    [anon_sym_AT2] = ACTIONS(24),
    [sym_content] = ACTIONS(26),
    [sym_dedent] = ACTIONS(32),
  },
  [7] = {
    [aux_sym__stanza] = STATE(2),
    [sym__primary_node] = STATE(40),
    [sym_block_node] = STATE(38),
    [sym_node] = STATE(40),
    [sym_ref_node] = STATE(40),
    [sym_binding] = STATE(63),
    [sym_ref] = STATE(18),
    [anon_sym_AT] = ACTIONS(5),
    [anon_sym_AT2] = ACTIONS(24),
    [sym_content] = ACTIONS(26),
    [sym_dedent] = ACTIONS(34),
  },
  [8] = {
    [aux_sym__stanza] = STATE(8),
    [sym__primary_node] = STATE(47),
    [sym_block_node] = STATE(41),
    [sym_node] = STATE(47),
    [sym_ref_node] = STATE(47),
    [sym_binding] = STATE(62),
    [sym_ref] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(20),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_AT2] = ACTIONS(36),
    [sym_content] = ACTIONS(39),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(24), 1,
      anon_sym_AT2,
    ACTIONS(26), 1,
      sym_content,
    STATE(4), 1,
      aux_sym__stanza,
    STATE(18), 1,
      sym_ref,
    STATE(38), 1,
      sym_block_node,
    STATE(63), 1,
      sym_binding,
    STATE(40), 3,
      sym__primary_node,
      sym_node,
      sym_ref_node,
  [27] = 8,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(24), 1,
      anon_sym_AT2,
    ACTIONS(26), 1,
      sym_content,
    STATE(5), 1,
      aux_sym__stanza,
    STATE(18), 1,
      sym_ref,
    STATE(38), 1,
      sym_block_node,
    STATE(63), 1,
      sym_binding,
    STATE(40), 3,
      sym__primary_node,
      sym_node,
      sym_ref_node,
  [54] = 8,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(24), 1,
      anon_sym_AT2,
    ACTIONS(26), 1,
      sym_content,
    STATE(6), 1,
      aux_sym__stanza,
    STATE(18), 1,
      sym_ref,
    STATE(38), 1,
      sym_block_node,
    STATE(63), 1,
      sym_binding,
    STATE(40), 3,
      sym__primary_node,
      sym_node,
      sym_ref_node,
  [81] = 8,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(24), 1,
      anon_sym_AT2,
    ACTIONS(26), 1,
      sym_content,
    STATE(7), 1,
      aux_sym__stanza,
    STATE(18), 1,
      sym_ref,
    STATE(38), 1,
      sym_block_node,
    STATE(63), 1,
      sym_binding,
    STATE(40), 3,
      sym__primary_node,
      sym_node,
      sym_ref_node,
  [108] = 4,
    ACTIONS(44), 1,
      anon_sym_AT2,
    ACTIONS(46), 1,
      sym_indent,
    STATE(33), 1,
      sym_children,
    ACTIONS(42), 5,
      sym_dedent,
      sym_newline,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [125] = 4,
    ACTIONS(50), 1,
      anon_sym_AT2,
    ACTIONS(52), 1,
      sym_indent,
    STATE(27), 1,
      sym_children,
    ACTIONS(48), 5,
      sym_newline,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [142] = 4,
    ACTIONS(44), 1,
      anon_sym_AT2,
    ACTIONS(52), 1,
      sym_indent,
    STATE(30), 1,
      sym_children,
    ACTIONS(42), 5,
      sym_newline,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [159] = 4,
    ACTIONS(46), 1,
      sym_indent,
    ACTIONS(50), 1,
      anon_sym_AT2,
    STATE(36), 1,
      sym_children,
    ACTIONS(48), 5,
      sym_dedent,
      sym_newline,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [176] = 4,
    ACTIONS(44), 1,
      anon_sym_AT2,
    ACTIONS(54), 1,
      sym_indent,
    STATE(46), 1,
      sym_children,
    ACTIONS(42), 4,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [192] = 4,
    ACTIONS(58), 1,
      anon_sym_AT2,
    ACTIONS(60), 1,
      sym_indent,
    STATE(39), 1,
      sym_children,
    ACTIONS(56), 4,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [208] = 4,
    ACTIONS(64), 1,
      anon_sym_AT2,
    ACTIONS(66), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_block_node_repeat1,
    ACTIONS(62), 4,
      sym_dedent,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [224] = 4,
    ACTIONS(71), 1,
      anon_sym_AT2,
    ACTIONS(73), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_block_node_repeat1,
    ACTIONS(69), 4,
      sym_dedent,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [240] = 4,
    ACTIONS(50), 1,
      anon_sym_AT2,
    ACTIONS(60), 1,
      sym_indent,
    STATE(44), 1,
      sym_children,
    ACTIONS(48), 4,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [256] = 4,
    ACTIONS(54), 1,
      sym_indent,
    ACTIONS(58), 1,
      anon_sym_AT2,
    STATE(45), 1,
      sym_children,
    ACTIONS(56), 4,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [272] = 4,
    ACTIONS(50), 1,
      anon_sym_AT2,
    ACTIONS(54), 1,
      sym_indent,
    STATE(43), 1,
      sym_children,
    ACTIONS(48), 4,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [288] = 4,
    ACTIONS(71), 1,
      anon_sym_AT2,
    ACTIONS(75), 1,
      sym_newline,
    STATE(26), 1,
      aux_sym_block_node_repeat1,
    ACTIONS(69), 4,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [304] = 4,
    ACTIONS(44), 1,
      anon_sym_AT2,
    ACTIONS(60), 1,
      sym_indent,
    STATE(37), 1,
      sym_children,
    ACTIONS(42), 4,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [320] = 4,
    ACTIONS(64), 1,
      anon_sym_AT2,
    ACTIONS(77), 1,
      sym_newline,
    STATE(26), 1,
      aux_sym_block_node_repeat1,
    ACTIONS(62), 4,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [336] = 2,
    ACTIONS(82), 1,
      anon_sym_AT2,
    ACTIONS(80), 5,
      sym_newline,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [347] = 2,
    ACTIONS(64), 1,
      anon_sym_AT2,
    ACTIONS(62), 5,
      sym_dedent,
      sym_newline,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [358] = 2,
    ACTIONS(64), 1,
      anon_sym_AT2,
    ACTIONS(62), 5,
      sym_newline,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [369] = 2,
    ACTIONS(86), 1,
      anon_sym_AT2,
    ACTIONS(84), 5,
      sym_newline,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [380] = 2,
    ACTIONS(90), 1,
      anon_sym_AT2,
    ACTIONS(88), 5,
      sym_newline,
      sym_mega_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [391] = 2,
    ACTIONS(94), 1,
      anon_sym_AT2,
    ACTIONS(92), 5,
      sym_indent,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [402] = 2,
    ACTIONS(86), 1,
      anon_sym_AT2,
    ACTIONS(84), 5,
      sym_dedent,
      sym_newline,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [413] = 2,
    ACTIONS(90), 1,
      anon_sym_AT2,
    ACTIONS(88), 5,
      sym_dedent,
      sym_newline,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [424] = 2,
    ACTIONS(94), 1,
      anon_sym_AT2,
    ACTIONS(92), 5,
      sym_indent,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [435] = 2,
    ACTIONS(82), 1,
      anon_sym_AT2,
    ACTIONS(80), 5,
      sym_dedent,
      sym_newline,
      sym_mega_newline,
      anon_sym_AT,
      sym_content,
  [446] = 2,
    ACTIONS(86), 1,
      anon_sym_AT2,
    ACTIONS(84), 4,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [456] = 3,
    ACTIONS(98), 1,
      anon_sym_AT2,
    ACTIONS(100), 1,
      sym_mega_newline,
    ACTIONS(96), 3,
      sym_dedent,
      anon_sym_AT,
      sym_content,
  [468] = 2,
    ACTIONS(104), 1,
      anon_sym_AT2,
    ACTIONS(102), 4,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [478] = 3,
    ACTIONS(98), 1,
      anon_sym_AT2,
    ACTIONS(100), 1,
      sym_newline,
    ACTIONS(96), 3,
      sym_dedent,
      anon_sym_AT,
      sym_content,
  [490] = 3,
    ACTIONS(98), 1,
      anon_sym_AT2,
    ACTIONS(106), 1,
      sym_mega_newline,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [502] = 2,
    ACTIONS(90), 1,
      anon_sym_AT2,
    ACTIONS(88), 4,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [512] = 2,
    ACTIONS(82), 1,
      anon_sym_AT2,
    ACTIONS(80), 4,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [522] = 2,
    ACTIONS(82), 1,
      anon_sym_AT2,
    ACTIONS(80), 4,
      sym_dedent,
      sym_newline,
      anon_sym_AT,
      sym_content,
  [532] = 2,
    ACTIONS(104), 1,
      anon_sym_AT2,
    ACTIONS(102), 4,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [542] = 2,
    ACTIONS(86), 1,
      anon_sym_AT2,
    ACTIONS(84), 4,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [552] = 3,
    ACTIONS(98), 1,
      anon_sym_AT2,
    ACTIONS(106), 1,
      sym_newline,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [564] = 2,
    ACTIONS(90), 1,
      anon_sym_AT2,
    ACTIONS(88), 4,
      sym_newline,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [574] = 2,
    ACTIONS(108), 1,
      anon_sym_AT2,
    ACTIONS(20), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_content,
  [583] = 4,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(110), 1,
      sym_content,
    STATE(29), 1,
      sym_node,
    STATE(56), 1,
      sym_binding,
  [596] = 2,
    ACTIONS(108), 1,
      anon_sym_AT2,
    ACTIONS(20), 3,
      sym_dedent,
      anon_sym_AT,
      sym_content,
  [605] = 4,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(112), 1,
      sym_content,
    STATE(28), 1,
      sym_node,
    STATE(65), 1,
      sym_binding,
  [618] = 3,
    ACTIONS(75), 1,
      sym_newline,
    ACTIONS(114), 1,
      sym_content,
    STATE(24), 1,
      aux_sym_block_node_repeat1,
  [628] = 3,
    ACTIONS(73), 1,
      sym_newline,
    ACTIONS(116), 1,
      sym_content,
    STATE(20), 1,
      aux_sym_block_node_repeat1,
  [638] = 2,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_COLON,
  [645] = 1,
    ACTIONS(122), 1,
      aux_sym_block_node_token1,
  [649] = 1,
    ACTIONS(124), 1,
      aux_sym_block_node_token1,
  [653] = 1,
    ACTIONS(126), 1,
      aux_sym_block_node_token1,
  [657] = 1,
    ACTIONS(128), 1,
      sym_identifier,
  [661] = 1,
    ACTIONS(130), 1,
      anon_sym_COLON,
  [665] = 1,
    ACTIONS(132), 1,
      sym_content,
  [669] = 1,
    ACTIONS(134), 1,
      aux_sym_block_node_token1,
  [673] = 1,
    ACTIONS(136), 1,
      aux_sym_block_node_token1,
  [677] = 1,
    ACTIONS(138), 1,
      sym_content,
  [681] = 1,
    ACTIONS(140), 1,
      aux_sym_block_node_token1,
  [685] = 1,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
  [689] = 1,
    ACTIONS(144), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 27,
  [SMALL_STATE(11)] = 54,
  [SMALL_STATE(12)] = 81,
  [SMALL_STATE(13)] = 108,
  [SMALL_STATE(14)] = 125,
  [SMALL_STATE(15)] = 142,
  [SMALL_STATE(16)] = 159,
  [SMALL_STATE(17)] = 176,
  [SMALL_STATE(18)] = 192,
  [SMALL_STATE(19)] = 208,
  [SMALL_STATE(20)] = 224,
  [SMALL_STATE(21)] = 240,
  [SMALL_STATE(22)] = 256,
  [SMALL_STATE(23)] = 272,
  [SMALL_STATE(24)] = 288,
  [SMALL_STATE(25)] = 304,
  [SMALL_STATE(26)] = 320,
  [SMALL_STATE(27)] = 336,
  [SMALL_STATE(28)] = 347,
  [SMALL_STATE(29)] = 358,
  [SMALL_STATE(30)] = 369,
  [SMALL_STATE(31)] = 380,
  [SMALL_STATE(32)] = 391,
  [SMALL_STATE(33)] = 402,
  [SMALL_STATE(34)] = 413,
  [SMALL_STATE(35)] = 424,
  [SMALL_STATE(36)] = 435,
  [SMALL_STATE(37)] = 446,
  [SMALL_STATE(38)] = 456,
  [SMALL_STATE(39)] = 468,
  [SMALL_STATE(40)] = 478,
  [SMALL_STATE(41)] = 490,
  [SMALL_STATE(42)] = 502,
  [SMALL_STATE(43)] = 512,
  [SMALL_STATE(44)] = 522,
  [SMALL_STATE(45)] = 532,
  [SMALL_STATE(46)] = 542,
  [SMALL_STATE(47)] = 552,
  [SMALL_STATE(48)] = 564,
  [SMALL_STATE(49)] = 574,
  [SMALL_STATE(50)] = 583,
  [SMALL_STATE(51)] = 596,
  [SMALL_STATE(52)] = 605,
  [SMALL_STATE(53)] = 618,
  [SMALL_STATE(54)] = 628,
  [SMALL_STATE(55)] = 638,
  [SMALL_STATE(56)] = 645,
  [SMALL_STATE(57)] = 649,
  [SMALL_STATE(58)] = 653,
  [SMALL_STATE(59)] = 657,
  [SMALL_STATE(60)] = 661,
  [SMALL_STATE(61)] = 665,
  [SMALL_STATE(62)] = 669,
  [SMALL_STATE(63)] = 673,
  [SMALL_STATE(64)] = 677,
  [SMALL_STATE(65)] = 681,
  [SMALL_STATE(66)] = 685,
  [SMALL_STATE(67)] = 689,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stanza, 2), SHIFT_REPEAT(55),
  [14] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stanza, 2), SHIFT_REPEAT(59),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stanza, 2), SHIFT_REPEAT(25),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__stanza, 2),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stanza, 2), SHIFT_REPEAT(67),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stanza, 2), SHIFT_REPEAT(17),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 1),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 3),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_node, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_node, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_node_repeat1, 2),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_node_repeat1, 2),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_node_repeat1, 2), SHIFT_REPEAT(52),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_node, 3),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_node, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_node_repeat1, 2), SHIFT_REPEAT(50),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_children, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__stanza, 1),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__stanza, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_node, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_node, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__stanza, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [142] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_puddlejumper_external_scanner_create(void);
void tree_sitter_puddlejumper_external_scanner_destroy(void *);
bool tree_sitter_puddlejumper_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_puddlejumper_external_scanner_serialize(void *, char *);
void tree_sitter_puddlejumper_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_puddlejumper(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_puddlejumper_external_scanner_create,
      tree_sitter_puddlejumper_external_scanner_destroy,
      tree_sitter_puddlejumper_external_scanner_scan,
      tree_sitter_puddlejumper_external_scanner_serialize,
      tree_sitter_puddlejumper_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
