steps:
  - label: ":bazel: Build"
    key: build
    commands:
      - nix develop -c bazel build //...

  - label: ":bazel: Test"
    commands:
      - nix develop -c bazel test //...
    key: test
    depends_on: build