@test:
    cargo test --features native

set positional-arguments

[no-cd]
@run *args='': (build "--features native")
    exec "{{justfile_directory()}}/target/debug/$(basename {{justfile_directory()}})" $@

@build *args='':
    cargo build $@