@test:
    cargo test --features native

[no-cd]
@run *args='': (build "--features native")
    exec "{{justfile_directory()}}/target/debug/$(basename {{justfile_directory()}})" {{args}}

@build *args='':
    cargo build {{args}}